//! Meshble core: the inspectable metamodel + the module versioning model.
//!
//! Difference from Odoo (see `docs/ANALISI_ODOO19.md`): a model definition is NOT
//! a class synthesized at runtime with `type()`, but inspectable static data;
//! extension is a VERIFIED MERGE, not a global monkey-patch; dependencies between
//! modules have verified VERSION RANGES (Odoo does not have them — see `docs/VERSIONING.md`).

mod action;
mod compute;
mod constraints;
mod domain;
mod manifest;
mod metamodel;
mod registry;
mod security;

pub use action::{
    action_for, actions_for, ActionFn, ActionInput, ActionOutcome, ActionRegistration,
};
pub use compute::{compute_fn, compute_on_read, compute_stored, computed_fields, has_read_computes, Children, ComputeFn, ComputeInput, ComputeRegistration};
pub use constraints::{check_constraints, has_constraints, ConstraintFn, ConstraintRegistration};
pub use domain::{json_string, Condition, Domain, DomainError, FieldBuilder, Operator, Sql, Value};
pub use manifest::{check_compat, resolve_module_set, ModuleDep, ModuleManifest, ResolutionError};
pub use metamodel::{resolve, validate_depends, validate_depends_with_extra, FieldDef, FieldKind, Model, ModelDescriptor, ResolvedModel};
pub use registry::{
    delegated_fields, external_tables, inherits_of, is_mailed, mailed_models, migration_plan,
    module_closure, module_of, registered_acls, registered_group_names, registered_model_names,
    registered_rules, related_path, resolve_all_registered, resolve_modules, resolve_registered,
    tracked_fields, AclRegistration, DelegatedField, ExternalTable, FieldExtension,
    InheritsRegistration, MailedRegistration, MigrationTarget, ModelRegistration, ModuleRegistration,
    RecordRuleRegistration, RelatedRegistration, TrackedFieldRegistration,
};
pub use security::{
    check_access, field_accessible, field_required_groups, record_rule_domain, Acl, Ctx,
    FieldGroupRegistration, Operation, RecordRule, RuleDomain,
};

// Re-export for the paths generated by the macros (`::meshble::inventory::submit!`).
pub use inventory;

/// Framework SemVer version (= workspace version). Modules compare it
/// against their own compatibility range via [`check_compat`].
pub const FRAMEWORK_VERSION: &str = env!("CARGO_PKG_VERSION");
