//! Meshble core: the inspectable metamodel + the module versioning model.
//!
//! Difference from Odoo (see `docs/ANALISI_ODOO19.md`): a model definition is NOT
//! a class synthesized at runtime with `type()`, but inspectable static data;
//! extension is a VERIFIED MERGE, not a global monkey-patch; dependencies between
//! modules have verified VERSION RANGES (Odoo does not have them — see `docs/VERSIONING.md`).

mod metamodel;
mod manifest;
mod registry;

pub use metamodel::{resolve, validate_depends, FieldDef, FieldKind, Model, ModelDescriptor, ResolvedModel};
pub use manifest::{check_compat, resolve_module_set, ModuleDep, ModuleManifest, ResolutionError};
pub use registry::{resolve_modules, resolve_registered, FieldExtension, ModelRegistration, ModuleRegistration};

// Re-export for the paths generated by the macros (`::meshble::inventory::submit!`).
pub use inventory;

/// Framework SemVer version (= workspace version). Modules compare it
/// against their own compatibility range via [`check_compat`].
pub const FRAMEWORK_VERSION: &str = env!("CARGO_PKG_VERSION");
