//! Inspectable model descriptors and extension resolution.

/// Logical type of a field. From this we derive the SQL type, UI widget, and API type.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum FieldKind {
    Text,
    Integer,
    /// `currency_field`: monetary field → "monetary" widget + linked currency.
    Decimal { currency_field: Option<&'static str> },
    Bool,
    Selection(&'static [(&'static str, &'static str)]),
    /// N→1 relation: generates an FK column.
    Many2one { target: &'static str },
    /// 1→N relation: does NOT generate a column (lives on the inverse).
    One2many { target: &'static str, inverse: &'static str },
}

/// Definition of a single field.
#[derive(Clone, Copy, Debug)]
pub struct FieldDef {
    pub name: &'static str,
    pub label: &'static str,
    pub kind: FieldKind,
    pub required: bool,
    /// `false` for non-stored computed fields → no column in the table.
    pub stored: bool,
    /// Name of the compute method, if computed.
    pub compute: Option<&'static str>,
    /// Declared dependencies; VERIFIED by `validate_depends` (no blind N+1).
    pub depends: &'static [&'static str],
}

impl FieldDef {
    /// A field has a column in the table iff it is stored and is not a one2many.
    pub fn has_column(&self) -> bool {
        self.stored && !matches!(self.kind, FieldKind::One2many { .. })
    }
    pub fn is_computed(&self) -> bool {
        self.compute.is_some()
    }
}

/// Descriptor of a model as defined by ONE module (the "base").
pub struct ModelDescriptor {
    pub name: &'static str,
    pub table: &'static str,
    pub fields: &'static [FieldDef],
}

/// Implemented by every model. In the walking skeleton it is written by hand;
/// in phase 2 it is generated by the `#[model]` proc-macro.
pub trait Model {
    fn descriptor() -> &'static ModelDescriptor;
}

/// RESOLVED descriptor: base + all extensions merged and validated.
/// This is the point — absent in Odoo — where the final definition is materializable.
#[derive(Debug)]
pub struct ResolvedModel {
    pub name: &'static str,
    pub table: &'static str,
    pub fields: Vec<FieldDef>,
}

/// Merges the base with the module extensions. Conflicts are errors.
pub fn resolve(
    base: &ModelDescriptor,
    extensions: &[&'static [FieldDef]],
) -> Result<ResolvedModel, String> {
    let mut fields: Vec<FieldDef> = base.fields.to_vec();
    for ext in extensions {
        for f in *ext {
            if fields.iter().any(|x| x.name == f.name) {
                return Err(format!(
                    "conflict: the field '{}' is already defined on the model '{}'",
                    f.name, base.name
                ));
            }
            fields.push(*f);
        }
    }
    Ok(ResolvedModel { name: base.name, table: base.table, fields })
}

/// Verifies that each `depends` points to an existing field (first segment of the path).
/// Antidote to Odoo's silent N+1: a broken dependency is an error, not a runtime bug.
pub fn validate_depends(m: &ResolvedModel) -> Result<(), String> {
    for f in &m.fields {
        for dep in f.depends {
            let first = dep.split('.').next().unwrap_or(dep);
            if !m.fields.iter().any(|x| x.name == first) {
                return Err(format!(
                    "the field '{}' depends on a non-existent field '{}' (in \"{}\")",
                    f.name, first, dep
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    static BASE: ModelDescriptor = ModelDescriptor {
        name: "demo.model",
        table: "demo_model",
        fields: &[FieldDef {
            name: "name", label: "Name", kind: FieldKind::Text,
            required: true, stored: true, compute: None, depends: &[],
        }],
    };

    #[test]
    fn resolve_detects_conflict() {
        static DUP: &[FieldDef] = &[FieldDef {
            name: "name", label: "X", kind: FieldKind::Text,
            required: false, stored: true, compute: None, depends: &[],
        }];
        assert!(resolve(&BASE, &[DUP]).is_err());
    }

    #[test]
    fn depends_on_unknown_field_errors() {
        static BAD: &[FieldDef] = &[FieldDef {
            name: "x", label: "X", kind: FieldKind::Integer,
            required: false, stored: true, compute: Some("c"), depends: &["nope"],
        }];
        let m = resolve(&BASE, &[BAD]).unwrap();
        assert!(validate_depends(&m).is_err());
    }
}
