//! Inspectable model descriptors and extension resolution.

/// Logical type of a field. From this we derive the SQL type, UI widget, and API type.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum FieldKind {
    Text,
    Integer,
    /// Non-exact floating point (Postgres `double precision`) — quantities, weights, factors, rates.
    /// For money use [`FieldKind::Decimal`] (exact).
    Float,
    /// `currency_field`: monetary field → "monetary" widget + linked currency.
    Decimal { currency_field: Option<&'static str> },
    Bool,
    /// Calendar date with no time (Postgres `date`).
    Date,
    /// Timestamp with time zone (Postgres `timestamptz`).
    Datetime,
    Selection(&'static [(&'static str, &'static str)]),
    /// N→1 relation: generates an FK column.
    Many2one { target: &'static str },
    /// 1→N relation: does NOT generate a column (lives on the inverse).
    One2many { target: &'static str, inverse: &'static str },
    /// N↔N relation through a junction table. No column on this model; the set lives in `relation`
    /// (a table with `column` → this model's id and `target_column` → the target's id). Read as an
    /// array of target ids; written with SET semantics (an array of ids replaces the membership).
    Many2many {
        target: &'static str,
        relation: &'static str,
        column: &'static str,
        target_column: &'static str,
    },
}

/// Definition of a single field.
#[derive(Clone, Copy, Debug)]
pub struct FieldDef {
    pub name: &'static str,
    pub label: &'static str,
    pub kind: FieldKind,
    pub required: bool,
    /// `false` for non-stored computed fields → no column in the table.
    pub stored: bool,
    /// Name of the compute method, if computed.
    pub compute: Option<&'static str>,
    /// Declared dependencies; VERIFIED by `validate_depends` (no blind N+1).
    pub depends: &'static [&'static str],
    /// Default value applied on create when the field is unset (as a string, parsed per kind).
    pub default: Option<&'static str>,
    /// Generates a single-column UNIQUE constraint in the DDL.
    pub unique: bool,
    /// A raw SQL CHECK expression (trusted, compile-time) generating a column CHECK constraint.
    pub check: Option<&'static str>,
}

impl FieldDef {
    /// A field has a column in the table iff it is stored and is not a one2many or many2many (those
    /// live on the inverse / a junction table).
    pub fn has_column(&self) -> bool {
        self.stored
            && !matches!(self.kind, FieldKind::One2many { .. } | FieldKind::Many2many { .. })
    }
    pub fn is_computed(&self) -> bool {
        self.compute.is_some()
    }
}

/// Descriptor of a model as defined by ONE module (the "base").
pub struct ModelDescriptor {
    pub name: &'static str,
    pub table: &'static str,
    pub fields: &'static [FieldDef],
}

/// Implemented by every model. In the walking skeleton it is written by hand;
/// in phase 2 it is generated by the `#[model]` proc-macro.
pub trait Model {
    fn descriptor() -> &'static ModelDescriptor;
}

/// RESOLVED descriptor: base + all extensions merged and validated.
/// This is the point — absent in Odoo — where the final definition is materializable.
#[derive(Debug, Clone)]
pub struct ResolvedModel {
    pub name: &'static str,
    pub table: &'static str,
    pub fields: Vec<FieldDef>,
}

/// Merges the base with the module extensions. Conflicts are errors.
pub fn resolve(
    base: &ModelDescriptor,
    extensions: &[&'static [FieldDef]],
) -> Result<ResolvedModel, String> {
    let mut fields: Vec<FieldDef> = base.fields.to_vec();
    for ext in extensions {
        for f in *ext {
            if fields.iter().any(|x| x.name == f.name) {
                return Err(format!(
                    "conflict: the field '{}' is already defined on the model '{}'",
                    f.name, base.name
                ));
            }
            fields.push(*f);
        }
    }
    Ok(ResolvedModel { name: base.name, table: base.table, fields })
}

/// Verifies that each `depends` points to an existing field (first segment of the path).
/// Antidote to Odoo's silent N+1: a broken dependency is an error, not a runtime bug.
pub fn validate_depends(m: &ResolvedModel) -> Result<(), String> {
    for f in &m.fields {
        // A non-stored (on-read) compute is evaluated same-record with no children loaded, so it
        // cannot aggregate over a relation. A dotted dependency there would silently read empty and
        // return a wrong value — reject it (a stored aggregate must declare `store`).
        let on_read = f.is_computed() && !f.has_column();
        for dep in f.depends {
            if on_read && dep.contains('.') {
                return Err(format!(
                    "the on-read computed field '{}' cannot depend on a relational path '{}' \
                     (non-stored computes are same-record only; add `store` to aggregate over children)",
                    f.name, dep
                ));
            }
            let first = dep.split('.').next().unwrap_or(dep);
            if !m.fields.iter().any(|x| x.name == first) {
                return Err(format!(
                    "the field '{}' depends on a non-existent field '{}' (in \"{}\")",
                    f.name, first, dep
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    static BASE: ModelDescriptor = ModelDescriptor {
        name: "demo.model",
        table: "demo_model",
        fields: &[FieldDef {
            name: "name", label: "Name", kind: FieldKind::Text,
            required: true, stored: true, compute: None, depends: &[], default: None, unique: false, check: None }],
    };

    #[test]
    fn resolve_detects_conflict() {
        static DUP: &[FieldDef] = &[FieldDef {
            name: "name", label: "X", kind: FieldKind::Text,
            required: false, stored: true, compute: None, depends: &[], default: None, unique: false, check: None }];
        assert!(resolve(&BASE, &[DUP]).is_err());
    }

    #[test]
    fn depends_on_unknown_field_errors() {
        static BAD: &[FieldDef] = &[FieldDef {
            name: "x", label: "X", kind: FieldKind::Integer,
            required: false, stored: true, compute: Some("c"), depends: &["nope"], default: None, unique: false, check: None }];
        let m = resolve(&BASE, &[BAD]).unwrap();
        assert!(validate_depends(&m).is_err());
    }

    #[test]
    fn on_read_compute_rejects_relational_depends() {
        // A non-stored compute cannot aggregate over a relation (children aren't loaded on read).
        static AGG: &[FieldDef] = &[FieldDef {
            name: "total", label: "T", kind: FieldKind::Integer,
            required: false, stored: false, compute: Some("c"), depends: &["name.x"], default: None, unique: false, check: None }];
        let m = resolve(&BASE, &[AGG]).unwrap();
        let e = validate_depends(&m).unwrap_err();
        assert!(e.contains("same-record only"), "rejects dotted depends on on-read compute: {e}");

        // A STORED compute with the same dotted dependency is fine (it aggregates at write time).
        static STORED: &[FieldDef] = &[FieldDef {
            name: "total", label: "T", kind: FieldKind::Integer,
            required: false, stored: true, compute: Some("c"), depends: &["name.x"], default: None, unique: false, check: None }];
        let m2 = resolve(&BASE, &[STORED]).unwrap();
        assert!(validate_depends(&m2).is_ok(), "stored aggregate may depend on a relational path");
    }
}
